### ISSUE TITLE
Video bitrate check not working (flow)

### ISSUE THREAD

**Issue by Technomancer-2048** [HaveAGitGat/Tdarr_Plugins#460]
I have been testing the video bitrate check flow block, but it always picks the default output 2, tested with Greaterthan 0 and Lessthan 100000000 which should match the test file, I have included a Run MKVPropEdit block before the check to update the details for the check.

**Comment by HaveAGitGat** [comment]
Thanks, yeah video stream bitrate can be a bit tricky as it's not always tagged by encoders or even when running mkvpropedit.

I've updated the plugin so it throws an error if no video bitrate is found:

https://github.com/HaveAGitGat/Tdarr_Plugins/pull/461/commits/98f8172dd025d7d16d2c5bf7ac1eb152890d44b6

**Comment by ohsnapword** [comment]
I am experiencing a similar issue.  The plugin cannot find the video bitrate for any MKV or MP4 file I've tested with.

**Comment by HaveAGitGat** [comment]
Hi, the `Tdarr_Plugin_00td_filter_by_bitrate` is not using the `video` stream bitrate but the overall file bitrate. The `Check Video Bitrate` plugin specifically checks the bitrate of the video stream which as you've seen is a little bit more tricky to have data for.

You can try something like this to run mkv propedit on the file to try and tag the video stream bitrate: 

![image](https://github.com/HaveAGitGat/Tdarr_Plugins/assets/43864057/ed5c7d69-d961-4bbd-897a-6e8881e44518)

I'll add a plugin for overall bitrate.

**Comment by HaveAGitGat** [comment]
Added `Check Overall Bitrate` https://github.com/HaveAGitGat/Tdarr_Plugins/pull/472/files

**Comment by fruitchewy** [comment]
I'm still seeing the same issue when running it through a MKVPropEdit step first. Should we just be using overall bitrate in general?

**Comment by HaveAGitGat** [comment]
2.12.01 released, added some improvements so should be working as expected. You could maybe use overall bitrate as a fallback in case video bitrate still not available

**Comment by Technomancer-2048** [comment]
Thanks very much for resolving this issue, it is working great now.

**Comment by HaveAGitGat** [comment]
Awesome thanks for letting me know

**Comment by 1-Felix** [comment]
Seems the issue still exists on `2.14.01`. I'm having the same error with some sample files like `sample__1080__libx265__flac__30s__video.mkv`.   Using the `Check Overall Bitrate` as a Fallback works though.

**Comment by HaveAGitGat** [comment]
@1-Felix click on that file in Tdarr you can see that neither ffprobe or medainfo have bitrate info for the video stream. This often needs to be tagged during encoding by the encoder. Sometimes this can be fixed by running mkv propedit on the file at the start of the flow using `Run MKVPropEdit` but unfortunately no way to guarantee this info.
